### PR TITLE
Increase upload max size 2mb -> 200mb (Fix #11)

### LINKED ISSUE #11: Change max upload size
This can be done by changing the configuration in the /etc/php5/fpm/php.ini file:

```
upload_max_filesize = 200M
post_max_size = 200M
```

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by moul** [comment]
cc @bchatelard @edouardb

**Comment by vikbez** [comment]
:+1:

**Comment by bchatelard** [comment]
:+1:

**Pull request merged**
